dalek-cryptography/bulletproofs

src/inner_product_proof.rs
This brings the implementation in sync with the notes.
=> Rename remaining x -> u in the IPP implementation

docs/notes.md
=> Clarify notes on how rangeproof is built up

.travis.yml
=> first try at travis

benches/bulletproofs.rs
The creation and verification benchmarks are done using Criterion's `bench_function_over_inputs` to run over a range of aggregation sizes, currently `m= 1,2,4,8,16,32`.
It is probably worth investigating the aggregate RP performance, since it seems slower, and also linear in the aggregation size (????):
```ascii
verify_rangeproof_n_32  time:   [674.08 us 674.33 us 674.60 us]
Aggregated 32-bit rangeproof verification/1                                                                             
time:   [2.2918 ms 2.2921 ms 2.2924 ms]
Aggregated 32-bit rangeproof verification/2                                                                             
time:   [4.2642 ms 4.2657 ms 4.2674 ms]
Aggregated 32-bit rangeproof verification/4 …
```
=> Add aggregate proof benchmarks

src/range_proof/mod.rs, src/range_proof/party.rs
@oleganza pointed out that when the dealer's polynomial challenge `x` is zero,
the parties will leak secrets, and suggested this check.
Informal analysis of the protocol flow:
dealer -> party: position
party -> dealer: `ValueCommitment`
The `ValueCommitment` cannot leak information to the dealer, since
it's blinded independently of any dealer messages
dealer -> party: `ValueChallenge`
Contains `y, z` challenges.
party -> dealer: `PolyCommitment`
Contains `T_1`, `T_2`, which are blinded independently from any
dealer messages and therefore can't leak information
dealer -> party: `PolyChallenge`
Contains `x` challenge
party -> dealer: `ProofShare`
Up till now, we know that the each of the party's messages can't
reveal info because they're blinded independently of the dealer
messages.  The …
=> Prevent a malicious dealer from retrieving the party's secrets

src/circuit_proof/mod.rs
=> Use CompressedRistretto in CircuitProof

docs/notes.md
Added the notes on how circuit math works - PTAL
Next steps - organize the notes better (table of contents or break into multiple files)
(remember to change references & copy duplicate footnotes)
=> Arithmetic circuit notes

Cargo.toml, benches/bulletproofs.rs, src/generators.rs, src/inner_product_proof.rs, src/lib.rs, src/range_proof/dealer.rs, src/range_proof/messages.rs, src/range_proof/mod.rs, src/range_proof/party.rs
Partially addresses #110.
Now each party's generators are their own independent chain.
=> Rework generators

Cargo.toml, benches/bulletproofs.rs, src/circuit_proof/circuit.rs, src/circuit_proof/r1cs.rs, src/generators.rs, src/inner_product_proof.rs, src/lib.rs, src/range_proof/dealer.rs, src/range_proof/messages.rs, src/range_proof/mod.rs, src/range_proof/party.rs, src/util.rs
This pulls:
- the reworked generators code (#128)
- the update to `curve25519-dalek` (#127)
=> Merge main into circuit to get reworked generators code

src/circuit_proof/mod.rs, src/circuit_proof/prover.rs, src/circuit_proof/verifier.rs, src/errors.rs, src/generators.rs, src/inner_product_proof.rs, src/range_proof/dealer.rs, src/range_proof/messages.rs, src/range_proof/mod.rs, src/range_proof/party.rs
The circuit-specific changes are in `circuit_proof/prover.rs` and `circuit_proof/verifier.rs`
=> Merge generators capacity changes into circuit

Cargo.toml, README.md
Also bumps the curve version to pick up serde support for compressed points.
=> Readme links

src/lib.rs
An add-on to #179 : we removed the doctest from that PR, so I'm adding the doctests back (using updated API) here.
=> Add doctest for r1cs proof

docs/aggregation-api.md, docs/notes.md
=> Clarify aggregation of RPs and CSs in the notes

src/circuit_proof/assignment.rs, src/circuit_proof/prover.rs, src/range_proof/party.rs, src/util.rs
=> Zero heap allocations in the circuit code

src/generators.rs
This adds documentation on how we construct the generators, and changes the default Pedersen generators to something that's not Bulletproofs-specific.
=> add doc on gens, change default pedersen gens

README.md, docs/notes.md, src/range_proof/mod.rs
I realized that there are some parts in the write-up that have a gap in explanation / require a big jump in understanding, and I’d like to fill those in a little more.
Also, fix up the rangeproof doctests & add an example doctest to the README.
Also, add some of the changes that were made to the notes (on the circuit branch) in this PR:
https://github.com/dalek-cryptography/bulletproofs/pull/191/files
=> Some note touchups

benches/r1cs.rs, docs/aggregation-api.md, src/errors.rs, src/r1cs/constraint_system.rs, src/r1cs/mod.rs, src/r1cs/proof.rs, src/r1cs/prover.rs, src/r1cs/tests.rs, src/r1cs/verifier.rs
More changes to the circuit code from yesterday.
Proposal: let's merge this into circuit, then merge `circuit` into `develop`, since now that we've done the prerelease we only have one development track.
=> some more circuit tweaks

Cargo.toml
=> Use stable dependencies

benches/r1cs.rs
Would fix #240. If this is not wanted, no big deal.
=> Refactor k-shuffle benchmark

src/errors.rs, src/r1cs/proof.rs, tests/r1cs.rs
Fixes #214 
~~I'm writing a roundtrip test, will update soon with a second commit.~~ Also ran cargo fmt on the respective commits.
=> Implements serialization of R1CS

benches/r1cs.rs, docs/r1cs-docs-example.md, src/r1cs/constraint_system.rs, src/r1cs/mod.rs, src/r1cs/prover.rs, src/r1cs/verifier.rs, tests/r1cs.rs
=> r1cs: decouple randomization from CS

Cargo.toml, benches/generators.rs, benches/range_proof.rs, src/generators.rs, src/inner_product_proof.rs, src/lib.rs, src/r1cs/mod.rs, src/r1cs/proof.rs, src/r1cs/prover.rs, src/r1cs/verifier.rs, src/range_proof/dealer.rs, src/range_proof/messages.rs, src/range_proof/mod.rs, src/range_proof/party.rs, src/transcript.rs, src/util.rs, tests/range_proof.rs
This runs `cargo fix --edition` and then `cargo fix --edition-idioms`.
=> Update to 2018 edition

docs/notes-r1cs.md
There are current some render problem on page https://doc-internal.dalek.rs/bulletproofs/notes/r1cs_proof/index.html. This pr should fix that.
=> fix latex render

Cargo.toml, src/generators.rs
Hi guys, I upgraded the dependencies to curve25519-dalek version 3.
Can you take a look at it?
=> Upgraded to curve25519-dalek version 3
