src/aggregated_range_proof/dealer.rs
src/aggregated_range_proof/messages.rs
src/aggregated_range_proof/mod.rs
src/aggregated_range_proof/party.rs
src/lib.rs
src/util.rs

Aggregated range proof enhancements

---

Cargo.toml
src/proof_transcript.rs

This PR implements a Duplex Keccak mode (see #55 for details). We also switch back to non-forked `tiny-keccak` crate so we can publish the bulletproofs crate.

ProofTranscript: use stock `tiny-keccak` crate with duplex construction

---

src/aggregated_range_proof/dealer.rs
src/aggregated_range_proof/messages.rs
src/aggregated_range_proof/mod.rs

- renames `Proof` to `AggregatedProof`
- moves the orchestration logic from the tests into a convenience `SinglePartyAggregator`
- refactors the test code to perform a full round trip of create → serialize → deserialize → verify

Add a `SinglePartyAggregator` and refactor test code

---

src/aggregated_range_proof/dealer.rs
src/aggregated_range_proof/mod.rs

(Follows #61, prelude to #60)
Moves the transcript state inside the dealer state. The reasoning is in the commit messages and in this thread: https://github.com/chain/ristretto-bulletproofs/issues/60#issuecomment-384742059

Keep dealer parameters internal to the dealer state

---

.travis.yml
benches/bulletproofs.rs

#76 broke the benchmarks because they weren't tested by CI.
This adds an empty `cargo bench` run to CI, so that no benches are run, but the benchmarks are compiled.

Fix the build and add benches to CI

---

benches/bulletproofs.rs
src/generators.rs
src/range_proof/dealer.rs
src/range_proof/messages.rs
src/range_proof/mod.rs
src/range_proof/party.rs

The `GeneratorsView` struct was originally intended to be a view into the
"full" (m,n) generators for a specific proof share.  But the
`Generators::all()` method gave a `GeneratorsView` that covered all of the
generators. This meant that `GeneratorsView` ended up having a duplicate role
to `&Generators`, and that it wasn't possible to tell whether a
`GeneratorsView` was for a specific share or was being used like a
`&Generators`.
This commit drops the `Generators::all()` method in order to fix this
inconsistency.

Clarify the `generators` API.

---

Cargo.toml
src/range_proof/dealer.rs
src/range_proof/messages.rs
src/range_proof/mod.rs
src/range_proof/party.rs
src/util.rs

- Ensure that no data is sent to the dealer twice (so it cannot be different)
- Pass the dealer's data into the proof share auditing
- Make auditing slightly more efficient
- Use `Sum` convenience functions
Co-authored-by: Cathie Yun <cathieyun@gmail.com>

Streamline messages in aggregation

---

.travis.yml
Cargo.toml
benches/bulletproofs.rs
src/generators.rs
src/inner_product_proof.rs
src/range_proof/dealer.rs
src/range_proof/messages.rs
src/range_proof/mod.rs
src/range_proof/party.rs

The main changes are:
1. `rand` moves to `0.5.0-pre.2` from `0.4`
2. Multiscalar multiplication uses traits now.
The first change allows us to use `OsRng` on `wasm32-unknown-unknown`
targets (which is implemented by FFI to the browser crypto APIs).
The second change allows us to drop in @oleganza's Pippenger branch with
a `[replace]` directive for testing large problem sizes.

Update to `curve25519-dalek` 0.17

---

src/inner_product_proof.rs
src/lib.rs
src/range_proof/dealer.rs
src/range_proof/messages.rs
src/range_proof/mod.rs
src/range_proof/party.rs
src/util.rs

This adds a canonical encoding algorithm for a RangeProof in form of `to_bytes`/`from_bytes` API. Serde trait is implemented in terms of these. 
The layout of an `2^n`-bit range proof is defined as:
* 4 compressed Ristretto points `A, S, T_1, T_2`,
* 3 scalars `t_x, t_x_blinding, e_blinding`,
* `2*n` pairs of compressed Ristretto points `L_0, R_0, ..., L_{n-1}, R_{n-1}`,
* two scalars `a` and `b`.
Total size: `32*(9+2*n)` bytes. 
64-bit range proofs are encoded in 672 bytes, 32-bit range proofs are encoded in 608 bytes.
Bonus: the compressed data is cached and reused in verification, so we do not incur unnecessary cost of compressing points that we decompressed just prior to verification.
PS. Serde is intentionally not implemented for IPP as we don't seem to be exposing it directly to …

Canonical serialization format for RangeProof

---

src/circuit_proof/mod.rs
src/inner_product_proof.rs
src/lib.rs
src/range_proof/dealer.rs
src/range_proof/mod.rs
src/util.rs

This pulls in the changes to use compressed points in the rangeproofs and inner product proofs.
The current circuit proof code stores the points in the circuit proof in uncompressed format, which is now inconsistent with the range proof code.  Maybe this PR should also change the circuit proofs to use compressed points?

Merge main into circuit

---

src/inner_product_proof.rs

Discussed here:
https://github.com/dalek-cryptography/bulletproofs/issues/107
IPP only works with power-of-two inputs, unless exceptions are specially programmed (e.g. length 0 inputs in when working with circuits). Add a check that the IPP inputs are meeting this requirement.

Enforce that `n` is 0 or power of 2 for IPP

---

src/circuit_proof/mod.rs
src/inner_product_proof.rs

`circuit.n` for circuits must be either 0 or a power of 2.
It is the responsibility of any circuit creators (e.g. `r1cs` module) to create circuits where `circuit.n` is a power of 2.
Discussed here: https://github.com/dalek-cryptography/bulletproofs/issues/107

Enforce lengths of inputs to circuit proofs

---

src/circuit_proof/mod.rs
src/circuit_proof/r1cs.rs

Part of r1cs circuit support plan: https://github.com/dalek-cryptography/bulletproofs/issues/118
This PR creates:
- r1cs format
- r1cs -> BP naive transformation
- r1cs circuits (e.g. shuffle and merge/split), and tests that they generate & verify proofs correctly

R1CS circuit frontend

---

src/circuit_proof/r1cs.rs

Makes sure r1cs → bp conversion pads circuits if `n` is not 0 or a power of 2.
A follow-up to PR https://github.com/dalek-cryptography/bulletproofs/pull/120 which enforces that inputs to circuit proofs must have `n` be 0 or a power of 2.
Discussed in this issue: https://github.com/dalek-cryptography/bulletproofs/issues/118

Pad circuits when creating them from `r1cs` format

---

Cargo.toml
src/errors.rs
src/inner_product_proof.rs
src/lib.rs
src/range_proof/dealer.rs
src/range_proof/messages.rs
src/range_proof/mod.rs
src/range_proof/party.rs

Closes #70.
The errors are split into two types, corresponding to each level of the range proof API.

Add failure-based error types.

---

Cargo.toml
src/errors.rs
src/inner_product_proof.rs
src/lib.rs
src/range_proof/dealer.rs
src/range_proof/messages.rs
src/range_proof/mod.rs
src/range_proof/party.rs

This doesn't change the circuit code to use error types (it leaves them as `&'static str` errors) because the circuit code is still in flux and I think that some of the possible errors could disappear if we changed the circuit code.

Merge RP error-handling into the circuit branch.

---

Cargo.toml
benches/bulletproofs.rs
src/inner_product_proof.rs
src/range_proof/messages.rs
src/range_proof/mod.rs
src/range_proof/party.rs
src/util.rs

This allows using the fallible multiscalar API with inline point decompression.
We also have to do an extra `.collect()` of some scalars, so that the iterators of scalars we feed into the MSM function have known lengths. This is because the upstream behaviour changed to enforce that the input iterators must have known lengths, preventing bugs like the ones @cathieyun was hitting.

Update to dalek 0.19

---

src/errors.rs
src/range_proof/mod.rs

Issue here: https://github.com/dalek-cryptography/bulletproofs/issues/108
Basically, when doing range proofs, check that `Generators` has `n` and `m` as powers of 2.

Check generator lengths in range proof

---

src/circuit_proof/r1cs.rs

- require user to pass in a `Transcript` and `Commitments` to `ConstraintSystem::new()`, such that:
- `ConstraintSystem` holds onto its own `Transcript`,
- `ConstraintSystem` takes the `Commitments` and inputs them into the `Transcript`, which should be the only time that the `Transcript` takes inputs from that `ConstraintSystem` instance
- add a `get_challenge` function to `ConstraintSystem` so that gadgets can get challenge variables from the `Transcript`
- make `Variable` `Copy`-able

Update R1CS API

---

src/circuit_proof/mod.rs
src/circuit_proof/prover.rs
src/circuit_proof/verifier.rs

This replaces the constant term in the `LinearCombination` struct by adding a new `Constant` variant to the `Variable` enum which represents 1.
I changed the example gadget to use it by changing `c2` to be a constant.  I'm not sure whether this is the best possible API yet. WDYT?

 Replace constant terms in LC by constant Variables 

---

Cargo.toml
src/range_proof/mod.rs

Merlin 0.3->0.4 changes the `TranscriptRng` API.  In Bulletproofs, we only used that for the verifier's randomness, but that randomness can just use a `thread_rng` since there's no secrets to leak.

Use Merlin v0.4

---

Cargo.toml

After this is merged into `main`, it can be cherry-picked into `circuit` for use in #166, #168.

Update to stable subtle 1.0, curve25519-dalek 0.20

---

Cargo.toml
README.md
benches/bulletproofs.rs
docs/aggregation-api.md
docs/notes.md
docs/range-proof-protocol.md
src/errors.rs
src/lib.rs
src/range_proof/dealer.rs
src/range_proof/messages.rs
src/range_proof/mod.rs
src/range_proof/party.rs

This adds `#![deny(missing_docs)]`, so it will probably require changes to the `circuit` branch the next time we sync the two branches (since it will force documenting all of the circuit API).
Closes #162

Add documentation and doctests to rangeproof code.

---

src/circuit_proof/assignment.rs

This is extremely useful in the `cloak` gadgets, where the prover is comparing assignment values to determine the values of intermediate variables.

Implement PartialEq for Assignment

---

benches/bulletproofs.rs
src/range_proof/dealer.rs
src/range_proof/messages.rs
src/range_proof/mod.rs
src/range_proof/party.rs

This streamlines error handling between the Party/Dealer and the non-MPC RangeProof API. 
Also the rangeproof is returned together with value commitments as compressed points for convenience. These must be computed internally anyway, and the user is liberated from computing them themselves.

Streamline range proof Party/Dealer APIs

---

src/circuit_proof/prover.rs
src/circuit_proof/verifier.rs

Addresses https://github.com/dalek-cryptography/bulletproofs/issues/148
All the checks are merged into one multi-scalar multiplication as described in the notes (#184):

Combine multiscalar mults in circuit verifier

---

Cargo.toml
src/lib.rs
src/range_proof/party.rs
src/util.rs

In the RangeProof implementation, each `Party` holds various secrets at different stages of the protocol. When the corresponding structure is consumed & dropped, the secrets must be cleared from memory before they can be part of uninitialized state of some other data.
This adds clearing of the secret data only, and a couple of tests that show that the method for clearing tuples and vectors actually works.

Clear secrets when dropped

---

docs/cs-proof.md
src/circuit_proof/mod.rs
src/circuit_proof/prover.rs
src/circuit_proof/tests.rs
src/circuit_proof/verifier.rs

This adds notes and implementation of a lower-level padding of the proof components as required by the inner product argument.
Closes #156

Efficient padding of the constraint system to a power-of-two multipliers

---

src/circuit_proof/assignment.rs
src/circuit_proof/prover.rs
src/range_proof/party.rs

Discussed here: 
https://github.com/dalek-cryptography/bulletproofs/pull/193#discussion_r226409056
>Manually clearing a few particular stack variables isn't really effective, because what you need to clear is both the secrets as well as all secret-derived data. For heap allocations, the idea is that the secret-derived data is probably going to live on the stack, so the only zeroing targets on the heap are the variables themselves. But if you want to try to clear stack data, you really need to wipe the entire stack. This is difficult because as the programmer, you don't actually control the stack allocation.
>
>More specifically, the commit that adds the clearing for stack variables makes mutable a bunch of data that should be immutable, but also doesn't actually erase all the stack data, …

Revert unsound attempt to clear secrets on the stack 

---

docs/notes.md

Other docs seem to use lo and hi, but at least this is self-consistent.  Might be worth picking one notation throughout all modules?

Use {lo,hi} instead of {L,R} where appropriate in notes module.

---

src/inner_product_proof.rs
src/range_proof/mod.rs

This patch eliminates blind allocation of `O(2^k)` array inside the inner product verification function based on the untrusted input of `O(k)` length.
For the rangeproof the cap is enforced in the rangeproof layer that caps the `2^k` to `64*<parties>` and for the constraint system it could be explicitly written as a metadata on a proof.

Explicitly cap allocations inside IPP verification

---

docs/range-proof-protocol.md

I believe there is a small typo

rangeproof: typo fix `y^-n` -> `y^-nm`

---

Cargo.toml
benches/generators.rs

I noticed BulletproofGens is quite slow with larger generator sizes. This commit adds a benchmark for both generators. Figured it may come in handy some day.

Add benchmarks for BulletproofGens and PedersenGens

---

src/r1cs/constraint_system.rs
src/r1cs/prover.rs
src/r1cs/verifier.rs
tests/r1cs.rs

This adds efficient and clean API for allocating one variable at a time.
Here is how it simplifies the code in Spacesuit and ZkVM: https://github.com/interstellar/slingshot/pull/211
Plus, the assignments are provided simply as `Option<Scalar>` and `Option<(Scalar,Scalar)>` to make code look nicer. The overhead in verifier of checking for `None` and not doing `Option::map` or something in the gadget code should be negligible.
Closes #206

r1cs: single-variable allocation API + simpler API for assignments

---

src/generators.rs

Adds `add_gens` for `BulletproofGens` so we can extend generators if they are not big enough

gens: dynamically growable BulletproofGens

---

benches/r1cs.rs
docs/r1cs-docs-example.md
src/r1cs/prover.rs
src/r1cs/verifier.rs
tests/r1cs.rs

This change allows users to provide Bulletproofs generators closer to the point where they are needed. This allows a prover, for instance, to know exactly how many multipliers were allocated to prepare a necessary number of generators, and also specify this number in the envelope that holds the proof. Verifier then also has an option to generate a necessary amount of generators based on actual usage, or preallocate as many as specified in the envelope (if not determined by some other factors).
For the verifier, the same thing is done for PedersenGens: since it does not create commitments, but only verifies them.
```rust
let p = Prover::new(&pc_gens, transcript);
...
let proof = p.prove(&bp_gens)?;
```
```rust
let v = Verifier::new(transcript);
...
v.verify(proof, &pc_gens, &bp_gens)?;
```

r1cs: provide BP generators later in the proving/verifying workflow

---

src/r1cs/proof.rs
src/r1cs/prover.rs
src/r1cs/verifier.rs
src/transcript.rs

If there were no second phase allocations, the proof is shorter by 3x32 bytes: second-phase commitments are treated as identity points.
If there were no randomization callbacks, the proof is domain-separated from one with randomization callbacks.
Note: it is possible to use randomized constraints, yet still perform no allocations in the second phase and receive a shorter proof. In this case the two-phase domain separator is still applied.
Closes #242
Closes #258 
Prior iteration: #258, diff: https://github.com/dalek-cryptography/bulletproofs/compare/oleg/optional-2phase...oleg/optional-2phase-tagged

r1cs: optional serialization for second-phase commitments with a version tag

---

src/r1cs/constraint_system.rs
src/r1cs/prover.rs
src/r1cs/verifier.rs

This adds method `transcript()` to the `ConstraintSystem` trait. The motivation is to allow higher-level protocol to bind the R1CS proof to data that's made available _during_ CS construction, but _not before_.
Example: in [ZkVM](https://github.com/interstellar/slingshot/blob/5377925ac10b13e0f6c958c4d037e13504cc21ce/zkvm/src/prover.rs#L108-L114) the transaction ID is computed via program execution that's also constructing a CS state. By the end of the execution, both the txid and set of constraints are known, and it's safer to bind the proof to the txid, but the transcript is exclusively held by the CS prover. This API allows to borrow the transcript from the CS prover to commit txid, and then complete computation of the R1CS proof.

r1cs: lease transcript from CS to bind proof to the data made available later

---

src/r1cs/linear_combination.rs

This is necessary for testing equality of higher-level data types in, e.g. [ZkVM](https://github.com/interstellar/slingshot/pull/287) (for use in tests, that is).

r1cs: add PartialEq to Variable and LinearCombination

---

CHANGELOG.md
Cargo.toml
README.md
benches/r1cs.rs
src/errors.rs
src/inner_product_proof.rs
src/r1cs/prover.rs
src/r1cs/verifier.rs
src/range_proof/dealer.rs
src/range_proof/mod.rs
src/transcript.rs
tests/r1cs.rs

This updates the develop branch with R1CS code to include the extra validation changes made in the main branch for 1.0.2.

Merge main into develop

---

Cargo.toml
src/generators.rs
src/range_proof/dealer.rs
src/range_proof/messages.rs
src/range_proof/party.rs

Addressing issues raised by the quarkslab audit (to be released soon):
* additional size validation for individual proof shares,
* correct `size_hint` for `AggregatedGensIter`,
* reused computation of powers-of-z in the proof aggregation to save a bit of CPU.

Better validation of proof shares in Range Proof MPC

---

Cargo.toml
src/errors.rs
src/generators.rs
src/inner_product_proof.rs
src/lib.rs
src/range_proof/dealer.rs
src/range_proof/messages.rs
src/range_proof/mod.rs
src/range_proof/party.rs
src/util.rs
tests/range_proof.rs

This change implements no_std support for the bulletproofs crate.  The changes are mostly mechanical.  This is the culmination several PRs worth of work, with changes to curve25519 and merlin crates already merged and released.
It was necessary to make minor modifications to some APIs, particularly in regards to RNGs.  As discussed by @isislovecruft in #275, the APIs in this change are backwards compatible for those building the crate in std mode.  So current users of the bulletproofs crate will see no change.  Users wishing to build bulletproofs in no_std mode will need to call the new *_with_rng prove and verfiy functions, and pass in a RNG.
This change is based on the main branch rather than the develop branch.  This is because the main branch in the dalek repo has several changes that …

Implement no_std support

---

Cargo.toml
benches/r1cs.rs
tests/r1cs.rs
tests/range_proof.rs

This is a breaking API change that will require a `2.0.0` version, but it keeps the crate up-to-date with the rand ecosystem. A possible further simplification of the dep tree would be to replace `clear_on_drop` by `zeroize`, but this could be done at any later point because `clear_on_drop` is an implementation detail.

Update rand_core, curve25519-dalek, merlin versions.

---

Cargo.toml
src/errors.rs
src/lib.rs
src/r1cs/proof.rs
src/range_proof/mod.rs

Because std::error::Error is not part of core, this commit feature-gates the
derived `Error` implementation on whether `std` is available.  If we are in a
`no_std` context, the `Error` enums are just plain enums with no `Error`
implementation.
Closes #306 
Follows on from #307, so this should be merged only after that one is.

Replace failure with thiserror to have std-compatible errors

---

src/r1cs/prover.rs
src/r1cs/verifier.rs
tests/r1cs.rs

This changes the Prover/Verifier API as follows:
1. Instead of holding `&mut Transcript`, Prover/Verifier accepts `BorrowMut<Transcript>`. This means, Transcript can be passed in not only as a mutable reference, but also moved in and owned by the constraint system.
2. `Verifier::verify` and `Prover::prove` have new variants `_and_return_transcript()` that return the transcript back to the user. So if the user moved the transcript into CS, they can get it back and continue working with it.
The proposed API allows users to "bundle" transcript and intermediate CS state in an object, so that it can be used after the CS is built, but before the proof is created/verified. Specifically, in [ZkVM](https://github.com/stellar/slingshot/blob/main/zkvm/src/verifier.rs), the transaction effects and …

r1cs: accept ownable transcript

---

src/r1cs/constraint_system.rs
src/r1cs/metrics.rs
src/r1cs/mod.rs
src/r1cs/prover.rs
src/r1cs/verifier.rs

Add methods to count the different kinds of constraints, which comes in handy when developing and benchmarking larger circuits. This is analogue with #284, `ConstraintSystem::multipliers_len()`.

R1CS: Add `constraints_len`, `deferred_constraints_len` and `total_constraints_len`

---

src/r1cs/constraint_system.rs
src/r1cs/prover.rs
src/r1cs/verifier.rs

It allows for the challenge phase to accept closures that take some more
context, e.g. moving non-Clone values in the challenge closure.
This works in stable since Rust 1.35; cfr.
https://github.com/rust-lang/rust/issues/28796.
This closes issue #244.
---
~~In other news: I'm not yet happy with the `'static` bound on the closures. Since I'm not yet worried about that kind of performance (just hacking around currently), I'm not going to fight the borrow checker there, yet.~~ Cfr #323

Make closure of challenge phase FnOnce.

---

src/r1cs/prover.rs

Development of complex constraint systems often goes wrong, and this patch allows to evaluate (for the prover) the actual value of a LinearCombination.
Related to #278, if it doesn't even fix that.

Set `Prover::eval` to pub, for easier debugging of circuits.

---

Cargo.toml
benches/linear_proof.rs
src/generators.rs
src/lib.rs
src/linear_proof.rs

In a recent paper, Gentry, Halevi, and Lyubashevsky introduced a technique for making a lightweight bulletproof for linear relations, which they call a linear proof. It is a proof of an inner product `<a, b> = c` where `a` is secret but `b` is public. This approach saves a factor of two in the number of exponentiations needed relative to a regular Bulletproofs inner product proof.
GHL21 paper (see section E.3): https://eprint.iacr.org/2021/1397.pdf
I implemented, tested, and benchmarked the code for the protocol, using similar techniques as found in the inner product proof.
Some notes:
- The verification equation in the paper is incorrect: the challenge `x_j` and inverse challenge `x_j^{-1}` are reversed. The correct equation is: `sum_{j=0}^{l-1} (x_j * L_j + x_j^{-1} * R_j)`. I will let …

Add Lightweight Bulletproof for Linear Relations
